export const scene1 = `
<?xml version="1.0" encoding="utf-8"?>
<!-- =================================================================================== -->
<!-- |    This document was autogenerated by xacro from src/catalogue/kompose/env.xacro | -->
<!-- |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED                                 | -->
<!-- =================================================================================== -->
<robot name="test-with-env">
  <link name="test-with-env_link"/>
  <joint name="test-with-env_link_worls_file_1_base_joint" type="fixed">
    <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
    <parent link="test-with-env_link"/>
    <child link="worls_file_1_link"/>
  </joint>
  <link name="worls_file_1_link">
    <visual>
      <geometry>
        <mesh filename="package://catalogue/meshes/43158824-940d-450f-ba7d-56e4f472fc6e.stl"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://catalogue/meshes/43158824-940d-450f-ba7d-56e4f472fc6e.stl"/>
      </geometry>
    </collision>
  </link>
</robot>

`